/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_build18_minesweepar_Overlay_Tile */

#ifndef _Included_com_build18_minesweepar_Overlay_Tile
#define _Included_com_build18_minesweepar_Overlay_Tile
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
