/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_build18_minesweepar_Overlay */

#ifndef _Included_com_build18_minesweepar_Overlay
#define _Included_com_build18_minesweepar_Overlay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_build18_minesweepar_Overlay
 * Method:    overlayTilesNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_build18_minesweepar_Overlay_overlayTilesNative
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
